-- MySQL Script generated by MySQL Workbench
-- Fri Sep 20 22:43:24 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

--
-- Se crea una base de datos con el nombre test_app
--
CREATE DATABASE IF NOT EXISTS test_app;

USE test_app;

-- 
-- Tabla propietario
-- 
CREATE TABLE IF NOT EXISTS `test_app`.`propietario` (
    `IDpropietario` BIGINT(12) NOT NULL AUTO_INCREMENT,
    `nombres` VARCHAR(45) NOT NULL,
    `apellidos` VARCHAR(45) NOT NULL,
    `correo_electronico_propietario` VARCHAR(75) NOT NULL,
    `telefono_propietario` VARCHAR(45) NOT NULL,
    `direccion_propietario` VARCHAR(45) NOT NULL,
    `ciudad_propietario` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`IDpropietario`),
    UNIQUE INDEX `idpropietario_UNIQUE` (`IDpropietario` ASC) VISIBLE,
    UNIQUE INDEX `telefono_propietario_UNIQUE` (`telefono_propietario` ASC) VISIBLE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `test_app`.`mascota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_app`.`mascota` (
  `IDmascota` BIGINT(12) NOT NULL AUTO_INCREMENT,
  `nombre_mascota` VARCHAR(45) NOT NULL,
  `especie` VARCHAR(45) NOT NULL,
  `raza` VARCHAR(45) NULL,
  `fecha_nacimiento_mascota` VARCHAR(45) NULL,
  `IDpropietario` BIGINT(12) NOT NULL,
  PRIMARY KEY (`IDmascota`, `IDpropietario`),
  INDEX `fk_mascota_propietario_idx` (`IDpropietario` ASC) VISIBLE,
  CONSTRAINT `fk_mascota_propietario`
    FOREIGN KEY (`IDpropietario`)
    REFERENCES `test_app`.`propietario` (`IDpropietario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_app`.`cuidador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_app`.`cuidador` (
  `IDcuidador` BIGINT(12) NOT NULL,
  `nombre_cuidador` VARCHAR(45) NOT NULL,
  `correo_electronico_cuidador` VARCHAR(45) NOT NULL,
  `telefono_cuidador` VARCHAR(45) NOT NULL,
  `tipo_cuidador` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IDcuidador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_app`.`paseador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_app`.`paseador` (
  `experiencia` INT NOT NULL,
  `tarifas` DECIMAL NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_app`.`entrenador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_app`.`entrenador` (
  `especialidad` INT NOT NULL,
  `certificaciones` VARCHAR(45) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_app`.`guarderia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_app`.`guarderia` (
  `direccion` VARCHAR(125) NOT NULL,
  `capacidad` INT NULL,
  PRIMARY KEY (`direccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_app`.`tienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_app`.`tienda` (
  `IDtienda` BIGINT(12) NOT NULL AUTO_INCREMENT,
  `nombre_tienda` VARCHAR(45) NOT NULL,
  `correo_electronico_tienda` VARCHAR(75) NOT NULL,
  `telefono_tienda` VARCHAR(15) NOT NULL,
  `direccion_tienda` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`IDtienda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_app`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_app`.`producto` (
  `IDproducto` BIGINT(12) NOT NULL AUTO_INCREMENT,
  `nombre_producto` VARCHAR(45) NOT NULL,
  `descripcion` TEXT(250) NULL,
  `precio` DECIMAL(2) NOT NULL,
  `IDtienda` BIGINT(12) NOT NULL,
  PRIMARY KEY (`IDproducto`, `IDtienda`),
  INDEX `fk_producto_tienda1_idx` (`IDtienda` ASC) VISIBLE,
  CONSTRAINT `fk_producto_tienda1`
    FOREIGN KEY (`IDtienda`)
    REFERENCES `test_app`.`tienda` (`IDtienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_app`.`servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_app`.`servicio` (
  `IDservicio` BIGINT(12) NOT NULL,
  `IDcuidador` BIGINT(12) NOT NULL,
  `descripcion_servicio` TEXT(250) NULL,
  `precio` DECIMAL NULL,
  `IDmascota` BIGINT(12) NOT NULL,
  `IDpropietario` BIGINT(12) NOT NULL,
  `tipo_servicio` VARCHAR(45) NULL,
  PRIMARY KEY (`IDservicio`, `IDcuidador`, `IDmascota`, `IDpropietario`),
  INDEX `fk_servicio_mascota1_idx` (`IDmascota` ASC, `IDpropietario` ASC) VISIBLE,
  INDEX `fk_servicio_cuidador1_idx` (`IDcuidador` ASC) VISIBLE,
  CONSTRAINT `fk_servicio_mascota1`
    FOREIGN KEY (`IDmascota` , `IDpropietario`)
    REFERENCES `test_app`.`mascota` (`IDmascota` , `IDpropietario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servicio_cuidador1`
    FOREIGN KEY (`IDcuidador`)
    REFERENCES `test_app`.`cuidador` (`IDcuidador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_app`.`Agenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_app`.`Agenda` (
  `IDagenda` INT NOT NULL,
  `fecha` DATE NULL,
  `hora_inicio` TIME NULL,
  `hora_fin` TIME NULL,
  `IDservicio` BIGINT(12) NOT NULL,
  `IDmascota` BIGINT(12) NOT NULL,
  `IDpropietario` BIGINT(12) NOT NULL,
  PRIMARY KEY (`IDagenda`, `IDservicio`, `IDmascota`, `IDpropietario`),
  INDEX `fk_Agenda_servicio1_idx` (`IDservicio` ASC, `IDmascota` ASC, `IDpropietario` ASC) VISIBLE,
  CONSTRAINT `fk_Agenda_servicio1`
    FOREIGN KEY (`IDservicio` , `IDmascota` , `IDpropietario`)
    REFERENCES `test_app`.`servicio` (`IDservicio` , `IDmascota` , `IDpropietario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test_app`.`modalidad_entrenamiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_app`.`modalidad_entrenamiento` (
  `IDmodalidad` INT NOT NULL,
  `tipo_modalidad` VARCHAR(45) NOT NULL,
  `IDservicio` BIGINT(12) NOT NULL,
  PRIMARY KEY (`IDmodalidad`, `IDservicio`),
  INDEX `fk_modalidad_entrenamiento_servicio1_idx` (`IDservicio` ASC) VISIBLE,
  CONSTRAINT `fk_modalidad_entrenamiento_servicio1`
    FOREIGN KEY (`IDservicio`)
    REFERENCES `test_app`.`servicio` (`IDservicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
